src/Entity/Tours.php
<?php

namespace App\Entity;

use App\Repository\ToursRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ToursRepository::class)]
class Tours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $destination = null;

    #[ORM\Column(length: 50)]
    private ?string $Hotel = null;

    #[ORM\Column(length: 50)]
    private ?string $Transport = null;

    #[ORM\Column(length: 50)]
    private ?string $type = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $details = null;

    #[ORM\Column(length: 400)]
    private ?string $img = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): static
    {
        $this->destination = $destination;

        return $this;
    }

    public function getHotel(): ?string
    {
        return $this->Hotel;
    }

    public function setHotel(string $Hotel): static
    {
        $this->Hotel = $Hotel;

        return $this;
    }

    public function getTransport(): ?string
    {
        return $this->Transport;
    }

    public function setTransport(string $Transport): static
    {
        $this->Transport = $Transport;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getDetails(): ?string
    {
        return $this->details;
    }

    public function setDetails(?string $details): static
    {
        $this->details = $details;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): static
    {
        $this->img = $img;

        return $this;
    }
}

src/Controller/TourDialsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Tours;
use App\Repository\ToursRepository;

class TourDialsController extends AbstractController
{
    #[Route('/dials', name: 'app_dials')]
    public function createAction(ToursRepository $toursDials): Response
    {
        $dials = $toursDials->findAll();
        return $this->render(
            "travel_agency/dials.html.twig",
            [
                "dials" => $dials
            ]
        );
    }

    #[Route('/details/{id}', name: 'app_details')]
    public function tourDetails(ToursRepository $toursDials, $id): Response
    {
        $dials = $toursDials->find($id);
        return $this->render(
            "travel_agency/details.html.twig",
            [
                "dials" => $dials
            ]
        );
    }
}

src/Controller/TravelAgencyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TravelAgencyController extends AbstractController
{
    #[Route('/', name: 'app_travel_agency')]
    public function index(): Response
    {
        return $this->render('travel_agency/index.html.twig', [
            'controller_name' => 'TravelAgencyController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Travel with us{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&family=Urbanist:wght@200&display=swap" rel="stylesheet">
        <link href="{{asset("css/style.css")}}" rel="stylesheet">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
    {% include "components/navbar.html.twig" %}
        {% block body %}{% endblock %}
        
{% include "components/footer.html.twig" %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

templates/components/footer.html.twig
<div class="card footer">
  <div class="card-header">
    Quote of the day
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>  INVESTMENT IN TRAVEL IS AN INVESTMENT IN YOURSELF. </p>
      <footer class="blockquote-footer">MATTHEW KARSTEN</footer>
    </blockquote>
  </div>
</div>

templates/components/navbar.html.twig
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><img src="photos/travel.png" width="50px"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/dials">Best Dials</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>

templates/tour_dials/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TourDialsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/olga/Desktop/Symfony-Day-2/src/Controller/TourDialsController.php'|file_link(0) }}">src/Controller/TourDialsController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/olga/Desktop/Symfony-Day-2/templates/tour_dials/index.html.twig'|file_link(0) }}">templates/tour_dials/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/travel_agency/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TravelAgencyController!{% endblock %}

{% block body %}
<h2 class="text-center">{{dials.destination}}</h2>


<div class="card">
 
  <div class="card-body">
    <h5 class="card-title">{{dials.hotel}}</h5>
    <p class="card-text">{{dials.details}}</p>
    <a href="#" class="btn btn-primary">Book a Trip</a>
  </div>
</div>




{% endblock %}

templates/travel_agency/dials.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TravelAgencyController!{% endblock %}

{% block body %}
<h2 class="text-center mt-5 mb-5">Hurrry Up to Book!</h2>

<div class="row row-cols-lg-3 row-cols-md-2 row-cols-xs-1 m-auto">
{% for x in dials %}
    <div class="container d-flex justify-content-around">
        <div class ='card p-0 mt-3 rounded-0' style='width: 330px; height: 70px rounded-0'>
            <img src="{{x.img}}" class="card-img-top rounded-0" alt="..."  style= 'height: 200px'>
            <div class="card-body">
                <h4 class='card-title'>Destination: {{x.destination}}</h4>
                    <p class='card-text'>{{x.hotel}} Hotel</p>
                    <p class='card-text'>Transport: {{x.transport}}</p>
                    <p class='card-text'>Good choice for {{x.type}}</p>
                    <h4 class='card-text mt-3'>From {{x.price}} $</h4>
            </div>
             <div class='text-center m-2'><a href='' class='btn btn-info'>Details</a>
            <a href='' class='btn btn-info'>Book a Trip</a></div>
        </div>
    </div>




{% endfor %}
</div>
{% endblock %}

templates/travel_agency/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TravelAgencyController!{% endblock %}

{% block body %}
<div class="container text-center mt-5">
        <div class="main-text">
            TRAVEL WITH SKYTOURS
        </div>
        <div class="title">Travel to USA</div>
        <div class="row">
            <div class="col-6 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2016/11/23/15/32/pedestrians-1853552_1280.jpg" alt="" width="600px"></div>
            <div class="col-6 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2016/09/15/18/59/golden-gate-bridge-1672473_1280.jpg" alt="" width="600px"></div>
        </div>
        <div class="title">Travel to Europe</div>
        <!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
        <div class="row">
            <div class="col-6 col-md-4 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2014/11/13/23/34/palace-530055_1280.jpg" alt="" width="390px"></div>
            <div class="col-6 col-md-4 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2018/07/18/20/25/channel-3547224_1280.jpg" alt="" width="390px"></div>
            <div class=" col-6 col-md-4 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2017/08/07/10/05/neuschwanstein-2602208_1280.jpg" alt="" width="390px"></div>
        </div>
        <div class="title">Travel to Asia</div>
        <!-- Columns are always 50% wide, on mobile and desktop -->
        <div class="row">
            <div class="col-6 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2016/11/07/14/03/japan-1805865_1280.jpg" alt="" width="600px"></div>
            <div class="col-6 mt-2"><img class="image" src="https://cdn.pixabay.com/photo/2021/11/25/15/28/temple-6823939_1280.jpg" alt="" width="600px"></div>
        </div>
    </div>
{% endblock %}